import{createMouseInputService,type MousePollingSource}from'../../../browser/mouse-input-service';import{calculatePollingRate}from'./mouse-polling-measurement';
export interface MousePollingController{stop():void;destroy():void}
const requireElement=<T extends Element>(root:ParentNode,s:string):T=>{const el=root.querySelector<T>(s);if(!el)throw new Error(`Mouse Polling Rate Test is missing ${s}`);return el;};
const sourceLabel=(source:MousePollingSource|null):string=>source==='raw-pointer'?'High-frequency pointer updates':source==='coalesced-pointer'?'Coalesced pointer samples':source==='basic-pointer'?'Basic browser pointer events':'Waiting';
export const mountMousePollingTest=(root:HTMLElement):MousePollingController=>{const surface=requireElement<HTMLElement>(root,'[data-polling-surface]');const start=requireElement<HTMLButtonElement>(root,'[data-polling-start]');const status=requireElement<HTMLElement>(root,'[data-polling-status]');const rate=requireElement<HTMLElement>(root,'[data-polling-rate]');const source=requireElement<HTMLElement>(root,'[data-polling-source]');let service=createMouseInputService(surface,'polling');let unsubscribe:()=>void=()=>undefined;let active=false;let destroyed=false;let timestamps:number[]=[];let timer:number|null=null;
 const clearTimer=():void=>{if(timer!==null){window.clearTimeout(timer);timer=null;}}; const detach=():void=>{clearTimer();active=false;unsubscribe();unsubscribe=()=>undefined;service.stop();start.disabled=false;};
 const cancel=():void=>{if(!active)return;detach();status.textContent='Test cancelled — keep this page visible and try again.';rate.textContent='—';};
 const finish=():void=>{if(!active)return;const selected=service.getPollingSource();const result=calculatePollingRate(timestamps);detach();source.textContent=sourceLabel(selected);if(!result){status.textContent='Not enough movement — try again.';rate.textContent='—';return;}status.textContent='Measurement complete';rate.textContent=`${result.observedRateHz} Hz`;};
 const handleStart=():void=>{if(active||destroyed)return;service.destroy();service=createMouseInputService(surface,'polling');timestamps=[];unsubscribe=service.subscribe((event)=>{if(event.type==='poll-samples'&&active)timestamps.push(...event.timestamps);else if(event.type==='clear'&&active)cancel();});if(!service.start()){unsubscribe();status.textContent='Pointer sampling unavailable';source.textContent='Unavailable';return;}const selected=service.getPollingSource();source.textContent=sourceLabel(selected);active=true;start.disabled=true;rate.textContent='—';status.textContent='Measuring for 2 seconds…';timer=window.setTimeout(finish,2000);};
 start.addEventListener('click',handleStart);return{stop:()=>{if(active)cancel();else service.stop();},destroy:()=>{if(!destroyed){destroyed=true;detach();start.removeEventListener('click',handleStart);service.destroy();}}};};
